### ISSUE TITLE
[CI/CD] Git Actions house keeping 

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1381]
Below is the current list of actions that we have. There are duplicated and deprecated actions in it. Clean up this list by eliminating the actions that are no longer in use. Give good names to the remaining ones. Consider consolidating actions if possible.
![image](https://github.com/RuminantFarmSystems/MASM/assets/51127592/3b43714b-2b46-4e6b-bddc-0de0048bba11)

**Comment by ltp23** [comment]
- [x] Clear the workflows runs that are no longer relevant, using Github CLI API requests for bulk delete.
- [x] Delete `testing_pytest.yml` in a PR.
- [x] Combine pytest and mypy actions.
- [x] Write issue for combining the linting action to the combined actions yml file. #1451 
- [x] Write issue for combining the build-sphinx action to the combined actions yml file. #1452 
- [x] Write issue for the `set-output` command being deprecated soon. #1453 
- [x] Write issue for automating the cleanup of old action results. #1454 

---

The command I used for step 1 was

```
# Replace the workflow name. List the last 800 runs and keep the latest 300.
# The rate limit for this was 5000 requests per hour. It cost more than 1 request per deletion.

gh run list --limit 800 --workflow 'Test and Coverage' --json databaseId,createdAt | jq -r 'sort_by(.createdAt) | .[:-300] | .[] | .databaseId | @sh' | xargs -I{} gh run delete "{}"
```
