### ISSUE TITLE
Implement snow in RuFaS

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#317]
The snow water content in mm is used to determine the amount of sublimation/soil evaporation from a soil object on a given day (SWAT 2:2.3.3.1). But that snow water content may or may not be evaporated as well in this process, and is currently not tracked or adjusted anywhere.

**Comment by morrowcj** [comment]
It may or may not be possible to use a weather input to determine the amount of snow on the ground. Often weather stations track "accumulated snow" or similar.

**Comment by Isgotkowitz** [comment]
The lack of snow (and its insulating effect) is negatively impacting the accuracy of soil temperature in RuFaS, so implementing a fix for this issue is a high priority.

**Comment by Isgotkowitz** [comment]
Update: from our SMEs, some simple rules that can be used to have snow enter the system:
1. Precipitation on days when it is freezing should be considered snow.
2. The ratio of precipitation depth to snow depth is 1:10 (meaning 1 mm of precipitation = 10 mm of snow).

**Comment by Isgotkowitz** [comment]
Task list for implementing snowfall in RuFaS:
- [x] Add a snow content variable to `SoilData`. XS Closed by #848
- [x] Add snow to snow content in `SoilData` when snowfall occurs. S Closed by #848
  - _Note_: do not worry about areal depletion when adding snow to a field. Assume the fraction of field area that is covered by snow is always 1 when snow is present.
- [x] Implement snow melting. L Closed by #848
  - Implement `Snow` class in `soil/`
  - Determine snow temperature (eqn. 1:2.5.1)
  - Determine snow melt amount (eqn.'s 1:2.5.2, 3)
- [ ] Implement sublimation and integrate with `_cycle_water()` in the `Field` module. M Closed by #879 

__Note__: if there is a user input that SWAT provides a default for, use that default in the code.
