### ISSUE TITLE
Clean up Crop and Soil inputs in `input/` directory

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#769]
During the integration of `InputManager` into the Crop and Soil module, only the ARL and Barnyard simulation files were completely rewritten to be compatible with the metadata structure. There are currently a number of different Field input files that need to be rewritten and put together into new metadata files so that they can be run with the new input system.

The configurations that need to be rewritten are:
- [x] Multi crop - completed in #774 
- [ ] Swat - completed in #801
- [x] Testing - completed in #799
- [ ] Remove unused inputs - completed in #802

**Comment by PooyaHekmati** [comment]
@KFosterReed This issue seems to be related to our conversation a few days ago. Do you think it is adequate to have it in MS 2.5?
@Isgotkowitz do you have any LOE (Level of Effort) estimation for this issue?

**Comment by KFosterReed** [comment]
Thanks Pooya. I would prefer to have this done before our MS 2.5 deadline but understand if that is not feasible.

**Comment by PooyaHekmati** [comment]
> Thanks Pooya. I would prefer to have this done before our MS 2.5 deadline but understand if that is not feasible.

Sure, I'm going to talk with Ed to see how we can correctly prioritize this.

**Comment by Isgotkowitz** [comment]
@KFosterReed @PooyaHekmati I estimate the LOE to be low, and getting this task accomplished for Milestone 2 is reasonable.

For some of the input files, I don't know what their purpose or origin is, and in those cases it may just be better to delete them if we can't find any documentation for them on Basecamp. Worst case scenario, we find the documentation for them later on and bring them back from commits before they were deleted.
