### ISSUE TITLE
Address current design and implementation of `Weather`

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#836]
**Is your feature request related to a problem? Please describe.**
The current implementation of the `Weather` class is problematic in a number of ways:
- It is contained in `classes.py`, instead of being in its own file.
- The weather data it contains is kept in a series of two dimensional arrays, resulting in data access being complicated and error prone (#753).
- There is no validation of weather data when it enters RuFaS as input (#752), this can lead to RuFaS breaking because data is missing (#835).
- Documentation in `Weather` is lacking (#732)
- The complexity of how `Weather` is setup in its `init` method has prevented it from being tested at all.
And there are many more specific issues.

**Describe the solution you'd like**
Refactor `Weather` to follow a clearer, more flexible design so that it can be more easily utilized by other parts of RuFaS, have its behavior verified, and be more easily changed its requirements evolve.

***Task List***
- [x] Move `Weather` into its own file.
- [ ] Change data storage and access (#753)
- [ ] Validate weather data in `InputManager` (#752, #835)

Possible additional tasks
- [x] Integrate `CurrentWeather` into `Weather`.
~~[ ] Make it possible to have multiple sets of weather data.~~ (no longer requested; should just run multiple simulations with different weather conditions).

**Describe alternatives you've considered**

**Additional context**
While refactoring the Crop and Soil module we came up with a way to simplify accessing the weather. It is called `CurrentWeather`, and it is a class where a single instance contains all the weather conditions for that day. It makes it very convenient for passing weather into functions, because all the necessary information is bundled into one data structure. It is also important because it determines whether precipitation falls as rain or snow. It would be good to move `CurrentWeather` out of the `Field` module and put it at the same level as `Weather`.

**Comment by Isgotkowitz** [comment]
@PooyaHekmati can you please take a look at this description and let me know your thoughts? I would like to start working on the tasks soon but I want to make sure I'll be going in the right direction.

**Comment by Isgotkowitz** [comment]
Part of this addressing this issue should be removing the irrigation from Weather. Irrigation is a field management practice, not a weather condition. This step should be taken in coordination with addressing issue #1372.

**Comment by ltp23** [comment]
This issue is blocked by #1383 .

**Comment by ew3361zh** [comment]
All the remaining outlying issues listed here are now gathered in issue #1510.
