### ISSUE TITLE
Evaluate phosphorus dynamics of the Crop and Soil module

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#977]
- [x] Grazing manure phosphorus evaluated in #874
- [x] Chemical phosphorus evaluated in #985 
- [x] Machine-applied manure phosphorus evaluated in #987
